### ISSUE TITLE
Support for muted channels

### ISSUE THREAD

**Issue by danielsnider** [gpailler/Luxa4Slack#16]
Hi @gpailler,

Can you prevent the light from turning on for unread messages in **muted** channels?

PS: Your code works incredibly well! I'm really enjoying it. 🙏

**Comment by gpailler** [comment]
Hi @danielsnider,

Nice catch. I never muted a channel so I never tested the behavior in this situation. 

PS: Thanks for your kind feedback 👍

**Comment by gpailler** [comment]
In progress... https://github.com/Inumedia/SlackAPI/pull/226

**Comment by danielsnider** [comment]
👍😊👍
I'll try it out shortly!
