### ISSUE TITLE
The light doesn't go off/reset after reading the incoming message like it used to. 

### ISSUE THREAD

**Issue by AngryTech** [gpailler/Luxa4Slack#21]
The light doesn't go off/reset after reading the incoming message like it used to. You can go into preferences and click save to reset it though.

**Comment by cre8ieguy** [comment]
I'm seeing the same thing. Wonder what changed?

**Comment by gpailler** [comment]
It could be a change from Slack. I will take a look and check the latest SlackAPI library too. Do you see any error in the log file ?

**Comment by cre8ieguy** [comment]
Thanks @gpailler !  I can't see a log file, nor any events in event viewer. Can you please point me in the right direction?

**Comment by gpailler** [comment]
The log file should be named `Luxa4Slack.Tray.log` and created alongside `Luxa4Slack.Tray.exe` program. But if you have installed Luxa4Slack in program files and depending of your UAC settings, this file is maybe not created.

You can run `Luxa4Slack.Tray.exe` in administrator or edit `Luxa4Slack.Tray.exe.config` and change the path (from `${basedir}` to `${tempdir}` for example to have this file created.

If you see some errors in the log, you can send it here but pay attention to scramble all the personal tokens/informations.

**Comment by AngryTech** [comment]
I found no errors but I'm wondering if these lines are not being reset...
2021-04-27 08:03:45.8206|DEBUG|SlackNotificationAgent|HasUnreadMention: True
2021-04-27 08:03:45.8206|DEBUG|SlackNotificationAgent|HasUnreadMessage: True

**Comment by gpailler** [comment]
I finally found some time to investigate this issue and found that some Slack API used by Luxa4Slack are deprecated/retired (https://api.slack.com/methods/channels.history for instance).
I'm checking how I can use other Slack API to achieve the same result

**Comment by cre8ieguy** [comment]
Thanks @gpailler ... Sounds like a lot of work ... but would be so great if this worked again

**Comment by gpailler** [comment]
Hi @cre8ieguy 

Could you try to install the build from https://ci.appveyor.com/project/gpailler/luxa4slack/builds/39483028/artifacts ?
I made a fix that should resolve the issue but would like to get your feedback.

Thanks

**Comment by cre8ieguy** [comment]
Hey @gpailler - I've tested and so far so good, looks like it has been fixed. Thanks so much. If anything changes I will be sure to post here.

**Comment by gpailler** [comment]
Great! Thanks for your feedback.

I will publish a new official release of Luxa4Slack.

**Comment by AngryTech** [comment]
Thanks @gpailler!
