### ISSUE TITLE
Support more than one workspace?

### ISSUE THREAD

**Issue by danielsnider** [gpailler/Luxa4Slack#9]
Hi,

Thanks for the great tool!! Does it support more than one Slack workspace at once? Perhaps using multiple terminals, each with a different token? 

Can you update the README to make clear whether or not multiple work spaces are supported?

Thanks again!

**Comment by gpailler** [comment]
Currently, Luxa4Slack can monitor only one workspace and you cannot launch several instances because the Luxafor cannot be shared between processes.
Adding multi workspaces support is definitely a feature I should add

**Comment by danielsnider** [comment]
Would love to have this feature ❤!

**Comment by danielsnider** [comment]
@gpailler Terrific, wonderful! It works. ❤!
